### ISSUE TITLE
Search is Entire DB loaded?

### ISSUE THREAD

**Issue by vincejairam** [magiccodingman/Magic.IndexedDb#7]
Is the entire DB loaded into .NET memory to search? Steve Sanderson indicated this when he was using the Reshiru.Blazor.IndexedDB package, which these packages are leveraging.

https://blog.stevensanderson.com/2019/08/03/blazor-indexeddb/

**Comment by magiccodingman** [comment]
@vincejairam I don't believe so, but let me get back to you on this shortly. I don't think it is, but I never considered it would be in the first place. Because this is just interacting with the default Indexed DD API that's available so it should in theory just be working by default standards of Indexed DB :)

**Comment by magiccodingman** [comment]
@vincejairam I am utilizing Dexie.js which is a helpful wrapper around IndexedDb, but it's still utilizing the base IndexedDB API. Therefore, it's 100% using disk. My code is only building a nice way to utilize IndexedDb in C# within the Blazor framework. It does not by itself change where the data is stored.

**Comment by magiccodingman** [comment]
Closing because this should be answered :)

**Comment by vincejairam** [comment]
Thanks @magiccodingman  for looking into this further...

**Comment by magiccodingman** [comment]
@vincejairam Just a heads up. This update here https://github.com/magiccodingman/Magic.IndexedDb/pull/53 resolves this issue. Don't know if this is what you meant originally, but initially I was doing table operations with indexes. THough https://github.com/magiccodingman/Magic.IndexedDb/pull/53 isn't merged as of now (but will be merged and likely posted to nuget within the next 72 hours), I've introduced cursors, large refactors, and significantly refined query joining logic. There's some things about IndexDB that you can't stop from loading into memory, but this has improved what's loaded into memory drastically.

The next update plus a few more I'm planning will be taking this project to a completely different level. Cheers! Was just thinking about it when I was working on the PR.
