### ISSUE TITLE
Invalid cast from System.Decimal to 'System.Nullable`

### ISSUE THREAD

**Issue by mavramos** [magiccodingman/Magic.IndexedDb#8]
When data is retrieved and a parameter is null, the following error occurs:
Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Invalid cast from 'System.Decimal' to 'System.Nullable`1[[System.Int32, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]'.
      
Example:
 [MagicTable("Test", DbNames.Data)]
 public class TestDTO
 {
     [MagicPrimaryKey("IdTest")]
     public int IdTest { get; set; }

     public int? Age { get; set; }
 }
 
If Age is null it gives that message

**Comment by kortgat** [comment]
@mavramos I did a pull request that fixes the nullable properties.
